name: EasyAuth
version: "1.0.0"
api: ["1.0.0"]
author: Scallop
description: Login to server easily
main: cn.yescallop.easyauth.EasyAuth

permissions:
 easyauth.changepassword:
  default: true
 easyauth.changepassword.others:
  default: op
 easyauth.checkpassword:
  default: op
 easyauth.register:
  default: op
 easyauth.unregister:
  default: true
 easyauth.unregister.others:
  default: op